<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/jogwums/image/upload/v1554310041/Test1/Jonathan_Ogwumike_Passport_Photo.jpg" alt="Jonathan Ogwumike">
                        <h6>Jonathan Ogwumike</h6>
                        <p>Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/badm1a" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Jogwums" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@jonathanogwumike" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am an aspiring web developer and data analyst with an interest in technology, entrepreneurship and cryptocurrency</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>