<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php'; ?>
   <body class=" pi">
      <?php include 'partials/navbar.php'; ?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dmeoibkzo/image/upload/c_scale,h_1500,w_1500/v1554412090/Abubakar.png" alt="Abubakar Diallo">
                        <h6>Abubakar Diallo</h6>
                        <p>Front-End Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/@abruzy01" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/abruzy" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@dialloabubakar5861" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                        I am Abubakar Diallo, a Front-end developer with great passion for web development and experience with HTML, CSS, and JavaScript and its frameworks. I am continually on the quest to improve my skill-set and make the world a better place. 
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php'; ?>
</html>
