<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/eddieglowada/image/upload/v1554554079/new-profile-pic.png" alt="Ada Glory">
                        <h6>Ada Glory</h6>
                        <p>Front-end Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/AOgbonna" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/adaglory" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://adaglow.blogspot.com" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am front end designer aspiring to be a full stack developer
                         through my exprience with HNG internship 5.0</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML| CSS | JAVASCRIPT</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
