<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/afeezdev/image/upload/v1554479791/234_816_708_9828_20170510_142357.jpg" alt="Mark Essien">
                        <h6>Abdulyekeen Afeez Olawale</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="twitter.com/talk2wale09" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="github.com/talk2wale09/" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="medium.com/@afeezdev" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I'm Abdulyekeen Afeez Olawale. A Front-end Developer with over, I'm still at the beginner level and looking forward to be a Full Stack Developer</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | CSS| React</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
