<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/akanstein/image/upload/v1554476792/dp.jpg" alt="Akpan Akan">
                        <h6>Akpan Akan</h6>
                        <p>Full-stack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/akanstein" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/akanstein" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@akanstein" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a full-stack web developer and tech creative. I'm based in lagos, Nigeria. I enjoy creating amazing solutions and products. I work with ReactJS and VueJs on the front end, NodeJS and PHP back end. I also work with MongoDB and MySQL databases and other technologies and packages.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | React</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
