<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/aqueousbobo/image/upload/v1554538580/download.png" alt="Idahosa Akioya">
                        <h6>Idahosa Akioya</h6>
                        <p>Front-end Developer/UI/UX Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/donrozay" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/AqueousSolution" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@chrisyaks" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Idahosa is a designer who dabbles into HTML,CSS and some Javascript. He loves reading, playing chess and food. His ultimate hobby is watching the faces of guys weep when he whips them on FIFA/PES. He is an all round cool and phlegmatic guy and is a people person.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Bootstrap | Figma</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
