<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dl8m1mupd/image/upload/v1554566542/1551481397.9tmp4yAVji20181215_131431_2.jpg" alt="Kingsley Asifor">
                        <h6>Kingsley Asifor</h6>
                        <p>Back-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/kingsleyasifor" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Asifor" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@kingsleyasifor" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Kingsley Asifor is a highly skilled, solution-focussed Full Stack Web Developer with extensive experience in designing, developing and managing rich Internet driven applications, websites and databases. <br /><br />

						I am consistent and reliable with strong technical knowledge and a passion for learning, utilizing and adapting to new technology.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Kotlin</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>