<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/wrightway/image/upload/v1554512025/IMG_-38mqfm.jpg" alt="Augustine Igwe">
                        <h6>Augustine Igwe Uzochukwu</h6>
                        <p>Mern Stack developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/augustus_best09" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/augustinebest" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/augustinebest" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p> Augustine is a MERN stack developer who writes and teaches JavaScript, I love drawing on papers as a means of expressing my inner feelings and also love meeting, networking and building scalable platforms that help solve the societal problems.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | UI/UX</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
