<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/awesauban/image/upload/v1554714550/IMG_20180108_231316_570.jpg" alt="Tunde Sauban">
                        <h6>Tunde Sauban</h6>
                        <p>UI/UX Guy</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/iTundesignerd" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Awesauban" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@awesauban" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a lover of good designs and anything design. I am also python enthusiast (still in the learning process, and hoping to change the notion pretty soon, well i don't think that's possible. ). .</p>
                        <br />
                        <h6>Skills</h6>
                        <p>CorelDraw | Python | Figma</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
