<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/ayilara/image/upload/v1554390849/ayilara.png" alt="ayilara">
                        <h6>Ayilara Olamilekan Sodiq</h6>
                        <p>Front-End Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/ayilaraolami" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ayilaraolamilekan" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ayilarasodiqolamilekan" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Ayilara Olamilekan Sodiq, a Front End Developer. I am a student of Kwara State University Department of Agricultural and Biological Engineering, also i am a member of DSC(Developer Student Club).</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTM | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
