<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dr8hvxu4u/image/upload/v1554423656/azeez.jpg" alt="Abolade Eniseyin">
                        <h6>Abolade Eniseyin</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/EniseyinA" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/heniisbaba" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://www.medium.com/@Heniisbaba" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am guy who loves solving problems,maths and coding. I am a backend developer who employs PHP and Javascript along with the Laravel Frameworks in building websites.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Laravel</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
