<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dsdt0mon2/image/upload/v1554513873/bmmmmm.jpg" alt="Mbah Ugochukwu">
                        <h6>Mbah ugochukwu</h6>
                        <p>Full stack web developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/boyznmarvis" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/boyznmarvis" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a tech lover,i am also a quick learner and always willing to try new things<br>
                        i am quite skilled in oop languages like java and c# precisely<br>
                       and most importantly i am a happy and friendly person </p>
                        <br />
                        <h6>Skills</h6>
                        <p>Css | php | Angular</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
