<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/codeleaf/image/upload/v1554380594/IMG_20171226_144620.jpg" alt="Adio Mojeed">
                        <h6>Adio Olanrewaju Mojeed</h6>
                        <p>Front-end Programmer/Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/adio_mojeed" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Adiomojeed" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@adio.mojeed" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, It's Mojeed here, A full stack web Developer focused on developing complex web projects and startups. Thanks to practice and experience. I produce responsive webpages, blogs, etc.<br>My jobs are qualified, time-efficient and I enjoy solving problems I am ready to collaborate with you to produce maximum output.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | C</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
