<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/codesage/image/upload/v1554382832/codesage.png" alt="Temiloluwa ojo">
                        <h6>Ojo Temiloluwa Philip</h6>
                        <p>Full-Stack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/THEMMYLOLUWAAA" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/themmyloluwaa" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@temiloluwaphilipojo" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Temiloluwa Ojo Philip, a self taught web developer and product manager skilled in html, css3, javascript, user experience and user interphase design. I am passionate about everything javascript and it is my goal to be skilled in all its applications on the web, mobile, and server. I am a constant learner, young and teachable. I am open to learning new technologies. I am open to job offers both remote and rellocation offers. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Product Management | UI/UX</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
