<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/thecodeghost/image/upload/v1554390384/IMG_2s0fmj.jpg" alt="Cole Eremoh Solomon">
                        <h6>Cole Eremoh Solomon</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="htps://twitter.com/thecodeghost" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/codecole" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@thecodeghost" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Cole, is  a Product Designer which skills varying from Interaction deisgn, Web design, Visual deisgn and UX engineering. I am a huge fan of javascript and front end technologies.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Phonegap| Figma</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
