<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dcoh3gq9l/image/upload/v1554314203/IMG-20190303-WA0006_5.png" alt="Mark Essien">
                        <h6>Sola-Aremu Oluwadara</h6>
                        <p>Software developer</p>
                        <ul class="list">
						<li><a href="https://twitter.com/Am_dapz" target="_blank"<i class="fab fa-twitter"></i></a></li>
                        <li><a href="https://github.com/dapzthelegend" target="_blank"<i class="fab fa-github"></i></a></li>
                        <li><a href="https://medium.com/@solaaremuoluwadara" target="_blank"<i class="fab fa-medium"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Good day, I’m Sola-Aremu Oluwadara. I’m a backend software engineer. 

I’m interested in everything programming,

and a great problem solver.

I’m participating in this year’s HNG internship to improve  my design skills

and pick up machine learning, as well as grasp other concepts</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | Android Studio | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
