<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/davidkathoh/image/upload/a_hflip/v1554390709/profile.jpg" alt="david kathoh ">
                        <h6>David Kathoh</h6>
                        <p>Android Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/DavidKathoh" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/davidkathoh" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@davidkathoh" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A software developer with proven ability to build user-centered and cutting-edge android applications. I am a natural problem solver who uses a combination of analytics, customer insights, and intuition to develop new products and features. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>Android SDK | JAVA | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
