<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/donc/image/upload/v1554525447/IMG_20170504_152320.jpg" alt="Donald Irebo">
                        <h6>Donald Irebo</h6>
                        <p>Back-End Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/DonaldIrebo" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/donald4u" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@donaldirebo_25464" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
						   <li><a href="https://www.linkedin.com/in/donald-irebo-b94168124/" target="_blank"<i class="fab fa-linkedin"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
						<p>A Computer Engineering graduate in love with Tech!</p>
                        <p><span style="font-weight: bolder;">Loves: </span> Back End Development.</p>
                        <p><span style="font-weight: bolder;">Dislikes: </span> Front End Development,Too much Design, Design...Design</p>
                        <p> <span style="font-weight: bolder;">Goals: </span> To be a better Back-End developer. </p>
                        <hr>
                        <h6>Skills</h6>
                        <p>JavaScript | Node.js |  PHP | MongoDB</p>
                        
                  
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
