<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <link rel="stylesheet" href="app/css/intern.css" type="text/css">
   <link rel="stylesheet" href="app/css/template.css" type="text/css">
   <link rel="stylesheet" href="app/css/doll.css" type="text/css">
   <link rel="stylesheet" href="app/css/app.css" type="text/css">
   <link rel="stylesheet" href="app/css/app.min.css" type="text/css">
   <link rel="stylesheet" href="app/css/dum.css" type="text/css">   
   <link rel="stylesheet" href="app/css/extra.css" type="text/css">
        
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue"  style = "width: 50px height:50px">
                        <img src="https://res.cloudinary.com/ebunalabi/image/upload/c_scale,w_234/v1554478103/Ebun_s_Digital.jpg" alt="Ebun Alabi">
                        <h6>Ebunoluwa Alabi</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Ebunoluwalabi" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/EbunAlabi" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ebun032555" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am passionate about developing solutions that can help optimize processes, save man hours, drive efficient decision making and ultimately deliver value that can be evaluated in monetary terms.</p>
                        <br/>
                        <h6>Skills</h6>
                        <p>JavaScript | BS4 | CSS | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
