<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/eniola/image/upload/v1554336932/Project/IMG_20180520_161028_2.jpg" alt="Eniola Erivona">
                        <h6>Eniola Erivona</h6>
                        <p>Web Development</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Erivona2" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/RivonEddy" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@eddycorp188" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Eniola Erivona. I am a web developer. I have been learning to code since 2018, and i have worked on variety of projects since then, thereby enhancing my knowledge in the IT world.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS| JavaScript | Java | Android </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
