<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/danielukene3/image/upload/v1554644032/evanaukene.png" alt="Evana Ukene">
                        <h6>Evana Ukene</h6>
                        <p>Software Developer/Big Data Enthusiast</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Ukeneh" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/evanaukene/" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@evanaukene/" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a Banker who is passionate about coding. I take out time from my long schedule to perfect my knowledge and application of Python. I'm also interested in doing Data Science which has led me take the classes offered by Google through coursera on the Data Engineering specialization. When I'm not coding or snooping around google cloud, you'd probably find me playing FIFA or PUBG.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
