<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dkufiberx/image/upload/v1554408644/resized.jpg" alt="Folasayo">
                        <h6>Folasayo Akinyosoye</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/folarmi" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https:medium.com/@fola4ril" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi,Am Folasayo, a front end Developer and a Teacher. I am glad to be on this Internship as i Learn to build real world application and collaborate with great Software Engineers</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML| Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>