<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/zicman/image/upload/v1554466652/zicpic.png" alt="Isaac Fadupin">
                        <h6>Isaac Fadupin</h6>
                        <p> Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/IsaacFadupin" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/IsaacFadupin" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@isaacfadupin" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, My name is Isaac,I'm a Tech Enthusiast who is passionate and intentional about every single thing he does. I'm into Software Development, Web Design and Motion Graphic Design.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>C# | SQL | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
