<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/fftcmjbj054/image/upload/v1554358137/PicsArt_04-04-07.05.10.jpg" alt="Mark Essien">
                        <h6> James Bamidele Johnson</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/JohnsonBamidel1" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/FFTCMJBJ054" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@jamesbamidelejohnson" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, My name is James Bamidele Johnson. I am a front end developer, an enthusiast with special interest in Information Technology. I am also a self motivated team worker with excellent commmunication skill and I am aspiring to be a full stack developer someday. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
