<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/wryhder/image/upload/v1554478472/me.jpg" alt="Mark Essien">
                        <h6>Jemimah Omodior</h6>
                        <p>Front-End Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/__Jemimah__" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Wryhder" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@Wryhder" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hey, there! I’m a front-end web developer with a preference for the more logic side of development with JavaScript. I’m a huge fan of 3d computer graphics and am currently building a web game to learn Three.js.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Python | Rust</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
