<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/jonahbanks/image/upload/v1554496714/pic_493.jpg" alt="Jonah Chukwuemeka">
                        <h6>Jonah Chukwuemeka</h6>
                        <p>Web Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/jonahbanks_" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/jonahbanks1" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@jonahbankki" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Jonah Chukwuemeka Banks, a young and vibrant web designer proficient in Python, HTML and Figma. I have strong knowledge of designs and illustrations.
                        I look forward to working on new and exciting projects. contact me.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | Figma | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
