<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dvx4mohuu/image/upload/v1554388502/WhatsApp_Image_2017-09-23_at_22.52.05_1.jpg" alt="Juliet Ujah">
                        <h6>Juliet Ujah</h6>
                        <p>Support Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/OchanyaUjah" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/julietujah" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ujahochanya" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a self taught web designer, support engineer, volley ball addict based in Lagos.I'm currently part of a software company Flexisaf Edusoft Limited that focus basically on education.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | Javascript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
