<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/kudosen/image/upload/v1554358826/profile_picture.jpg" alt="Mark Essien">
                        <h6>Ubong Udosen</h6>
                        <p>Back-End Engineering Trainee</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/The_Ubong" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/kudosen" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@kudosen93" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am new to web development with enthusiasm too for backend development, been involved in a few successful group projects working comfortably with basic HTML, CSS, and C#. I learn well, better and faster on the job and that is why I chose to be part of the HNG Internship.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | C#</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
