<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/kingsley67/image/upload/v1554513967/IMG-20190102-WA0004.jpg" alt="Che_Kingsley">
                        <h6>Che Kingsley</h6>
                        <p>Android,Front-Back End Developper</p>
                        <ul class="list">
                           <li><a href="https://github.com/kingmax67" target="_blank"<i class="fab fa-facebook fa-2x"></i></a></li>
                           <li><a href="https://github.com/kingmax67" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="rdpress.com/checkout/educafric.wordpress.com" target="_blank"<i class="fab fa-wordpress fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Web Developper from Cameroon,love programming,technologies, football,and travelling. I also love challenges and accomplishing complicated tasks reasons why i'm at HNG Internship 5.0</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Java | PHP | </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>