<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/leafmandhunter/image/upload/v1554605103/mikke11ratio.jpg" alt="leafmanDHunter">
                        <h6>Michael Akhibemudu IKPEFUA</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/LeafmanDHunter" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/leafmanDHunter" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I was born in Lagos, later on, we moved to Jos, there I attained my primary and secondary School certificate. I studied Information Technology in Malaysia after-which I came to Nigeria. Am a passionate learner, I love programming. my hobbies are playing tennis game and traveling.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | Laravel | SQL</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
