<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/lekia/image/upload/v1554320457/Lekia.png" alt="Gospel Lekia">
                        <h6>Gospel Lekia</h6>
                        <p>BackEnd Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/goslek" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/yigaue" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@lekia" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a Passionate Back-end developer, an advocate of clean code. I take pleasure in learning new things, and I love to meet people.  I code in PHP, Laravel framework, HTML with a bit of Javascript. I look forward to improving my skills. I write when away from coding</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | PHP | CSS|LARAVEL</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
