<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/lesliecode/image/upload/v1554384369/passport.png" alt="Osioreamhe Ugheoke">
                        <h6>Osioreamhe Ugheoke</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Lescodec/Lescodec.github.io" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hello!!! I'm Osioreamhe Ugheoke a web developer for the past 18 months, I'm an ambitious developer working towards becoming a worldclass fullstack developer. I read physics in college but took a deep dive at Software Development and my life has been INTERESTING!!! ever since. Please hit the links to see my Git profile. Thank You!!!</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Java</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
