<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/mista-oba/image/upload/v1554335638/new_vbvlwe.jpg" alt="Abdulhafeez Babatunde">
                        <h6>Abdulhafeez Babatunde</h6>
                        <p>UI Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/mista_oba" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/mistaOba" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@mista_oba" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A UI/UX Designer, interested in building beautiful interfaces that solve problems and are easy-to-use. I am currently working on my front-end skills so I can bring my designs to life with code.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Figma | Adobe XD | Invision Studio</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
