<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/nath/image/upload/v1524182119/Image_-_Portrait.jpg" alt="Nathaniel Makinde">
                        <h6>Nathaniel Makinde</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/nathmankind" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/nathmankind" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@nathmankind/" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a frontend developer, love to build cool interface. An undergraduate student of ladoke akintola university of technology, studying pure and applied physics. I love tech and love creating solution for several problems through technology. I love music and i love good nigerian jollof.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
