<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/djtprypsz/image/upload/v1554665502/ngeezy19.png" alt="Ngozi Njeze">
                        <h6>Ngozi Njeze</h6>
                        <p>Full Stack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/ngeezy19" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ngeezy19" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="http://ngeezy.home.blog" target="_blank"><i class="fab fa-medium fa-2x" ></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a fullstack developer with 2 years experience. I have been part of projects across diverse industries using C#, Node, Angularjs.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | C# | Django</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
