<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/obongimo/image/upload/v1554344495/00971dc1-6afe-43b3-9c3c-28c2aa18a0d4.jpg" alt="Imoobong Akpan">
                        <h6>Imoobong Akpan</h6>
                        <p>Backend Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Obongimo" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/obongimo" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Imoobong Akpan is a full stack web developer who enjoys solving creative problems by coding. He also loves playing Chess and watching sports.</p>
                        <br />
                        <h6>Skills</h6>
                        <p> PHP | Javascript | mySql </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
