<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dlyuvm4rn/image/upload/v1554338186/1554108689532.jpg" alt="Mark Essien">
                        <h6>Eli Ogonna Precious</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Im eli ogonna precious,a 400level student of university if Nigeria,Nsukka.I'm a girl that likes coding.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | CSS | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
