<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/oliver-k/image/upload/v1554373476/avater/profile3.jpg" alt="Oliver Kelechi">
                        <h6>Oliver Kelechi</h6>
                        <p>Fullstack (node, react)</p>
                        <ul class="list">
                           <li><a href="https://web.facebook.com/kelechi.azorji" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Oliver-ke" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://twitter.com/KelechiOliver3" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                            <li><a href="https://medium.com/@kelechioliver96" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm Oliver, a young Nigerian who is very passionate about tech, I love coding, learning and working with team. I've done projects on web using node(most of the time), React and Django also as a hobby I programm microcontrollers like the arduino, esp32 and more. I just think tech rules the world</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Node | React | etc..</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
