<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/mmi/image/upload/v1554489021/Oyejide-HNG.jpg" alt="Oluwatobi Oyejide">
                        <h6>Oluwatobi Oyejide</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/oyejideoyetunji" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/oyejide1" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@moyejide2016" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi i'm Oluwatobi Oyejide a JavaScript proficient, STEM enthusiast and problem solver. Having my foundation in engineering, i am curently on a track to becoming a Full Stack Developer.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML & CSS </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
