<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                     <img src="https://res.cloudinary.com/oluwaseunmusa/image/upload/v1554379708/passport_new.jpg" alt="Oluwaseun Musa">
                        <h6>Oluwaseun Musa</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/oluwaseun_musa" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/oluwaseunmusa" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://www.medium.com/@oluwaseunmusa" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Oluwaseun, A Rockter Front-End Developr (Still Learning the Stacks), I am fancinated by detailed creative design which has increased my interest for Front-End. I belive the HNG Internship would help me to improve drasrically</p>
                        <br />
                        <h6>Skills</h6>
                        <p>UI Design | CSS | Average JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
