<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/oluwagreat/image/upload/v1554315211/hng5/IMG_20190318_095317.jpg" alt="oluwagreat">
                        <h6>Babalola Oluwatobi</h6>
                        <p>Full Stack Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Olutobiloba1" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/oluwagreat" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@oluwatobiloba1" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a self-taught programmer/ web developer who always craves to learn more technologies. I am knowledgeable in PHP, MySQL, Bootstrap, HTML, CSS, and JavaScript. I learn very fast and open to new challenges.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | MySQL | Bootstrap</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
