<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/precious-usanga/image/upload/v1554368340/samples/POPE.jpg" alt="Precious Usanga">
                        <h6>Precious Usanga</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/usanga_precious" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Precious-Usanga" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@precioususanga001" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hello,<br/>I am Usanga, Precious Augustine, a Computer Engineer and a Frontend Developer.<br/>
                        I have maximum interest for Computer and Software related fields and i’m open to all tasks and challenges that cross my path.<br/>
                        I love learning so as to become more proficient. I want to make an impactful career in the tech ecosystem.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
