<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/seyiprisca/image/upload/v1554832719/New_Doc_2017-04-14_1.jpg" alt="Olawale Oladele">
                        <h6>Priscilla Abimbola</h6>
                        <p> Data Analyst and budding Data Scientist</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/seyiabimbola4" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/seyiprisca/" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@brainypee" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Abimbola Priscilla, a graduate of biochemistry with interest and skill set in data analytics. I intend to solve biological and health challenges using technological tools most especially data anlytics and machine learning.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python | Javascript | MySQL | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
