<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/psychevisions/image/upload/v1554459432/IMG_20190330_161707-01.png" alt="Akande Samuel">
                        <h6>Akande Samuel</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/psychevisions" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/psychevisions" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@xammie.seun" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p> I am a filmmaker and digital marketer, i have always been interested in tech and i started coding january 2019, i am looking to improve, to learn more and be part of solutions that makes our way of life easier</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Css | Html</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
