<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/qausim/image/upload/v1554363874/qausim.png" alt="Olawumi Qauzeem Yusuff">
                        <h6>Olawumi Qauzeem Yusuff</h6>
                        <p>Android Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/qausim_yousuf" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/qausim" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@qauzeemyusuff" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                        I am a graduate of Mechanical Engineering who, fascinated by technology, decided to pursue a career in software
                        development. I have had a few self-learning opportunities that has opened me to languages like Python and JavaScript
                        and so far it has been fun.


                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | JavaScript | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
