<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dis3a42lz/image/upload/v1554324873/sama.jpg" alt="Samaila Bala">
                        <h6>Samaila Bala</h6>
                        <p>Full Stack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/samabalap" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/sa-ma" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@samailabalap" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Samaila Philemon Bala and I am not your average full stack web developer. Web development is fun to me and I play with new technologies in my spare time which in turn helps me churn out beautiful, modern, and functional products.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | NodeJs</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
