<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/soleday0/image/upload/v1554348935/my_image.jpg" alt="Soledayo Olagbegi">
                        <h6>Soledayo Olagbegi</h6>
                        <p>Scientist</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/soleday0" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="github.com/soleday0" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://soleday0.wordpress.com" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a scientist with special focus on GIS and geoscience</p>
                        <br />
                        <h6>Skills</h6>
                        <p>GIS| Matlab | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
