<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
    <?php include 'partials/navbar.php'; ?>
    <section class="main-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-6 col-xs-12">
                    <div class="col-md-6 col-xs-12">
                        <div class="intern-block border-blue">
                            <img src="https://res.cloudinary.com/catalyst-creative-concepts/image/upload/v1554456411/my_passport50.jpg" alt="Mark Essien">
                            <h6>Temitope Bamidele</h6>
                            <p>Back-end Engineer</p>
                            <ul class="list">
                                <li><a href="https://twitter.com/SirCatalyst" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://github.com/sircatalyst" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                                <li><a href="https://medium.com/@temibami" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 align-items-center">
                        <div class="intern-bio border-blue">
                            <h6>About me</h6>
                            <p>I am a Full Stack Developer. I am a fast learner and great collaborator. I love challenges and problem-solving. I am open to innovative ideas. And, I hope to change the world through technology.</p>
                            <br />
                            <h6>Skills</h6>
                            <p>MERN JS | PHP | PHOTOSHOP</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>