<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dujca0vw6/image/upload/v1554331237/smartbiz.jpg" alt="Victor Etudor">
                        <h6>Victor Etudor</h6>
                        <p>Frontend Engineer </p>
                        <ul class="list">
                           <li><a href="https://twitter.com/VictorEtudor" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/victoretudor" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="http://www.clickagromarket.com/blog" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A frontend developer, Experienced Entrepreneur with a demonstrated history of working and consulting in the food production.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | Javascript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
