<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/southside/image/upload/v1554727762/profile_picture_cropped.jpg" alt="Abdulsalam Opeyemi">
                        <h6>Abdulsalam Opeyemi</h6>
                        <p>Android developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/south_side_24" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/southside24" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@abdulsalamopeyemi" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A graduate from the university of Ibadan, interested in improving his coding skills, already developing applications for mobile phones powered by android operating system. Skilled in Java and JavaScript.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | JavaScript | Firebase</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
