<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/stanliwise/image/upload/v1554597798/IMG_20180819_0920_4.png" alt="Mark Essien">
                        <h6>Aloh Stanley</h6>
                        <p>Back-end engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/stanliwise" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/stanliwise" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="http://2daydeveloper.blogspot.com" target="_blank"<i class="fab fa-blogger fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Aloh Stanley Benjamin, I am a tenacious coder, I love everything about IT technologies and I look forward becoming a renowed developer someday.
                        I try to learn as much as I can to Improve everyday.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | JavaScirpt | Java </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
