<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
   <?php include 'partials/navbar.php'; ?>
   <section class="main-section">
      <div class="container">
         <div class="row">
            <div class="col-md-12 col-sm-6 col-xs-12">
               <div class="col-md-6 col-xs-12">
                  <div class="intern-block border-blue">
                     <img src="https://res.cloudinary.com/brianiyoha/image/upload/v1554465575/DSC_0960_xp3pen.jpg" alt="Brian Iyoha">
                     <h6>Brian Iyoha</h6>
                     <p>Back-end Engineer</p>
                     <ul class="list">
                        <li><a href="https://twitter.com/thecodearcher" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                        <li><a href="https://github.com/thecodearcher" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                        <li><a href="https://medium.com/@brian.iyoha" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-md-6 col-xs-12 align-items-center">
                  <div class="intern-bio border-blue">
                     <h6>About me</h6>
                     <p>I like to call myself a developer of all things JS. But basically, I love to build
                        stuff that solves a problem irrespective of the technology involved.
<br/>
<br/>
                        When I'm not coding, I write, play games and get fat.</p>
                     <br />
                     <h6>Skills</h6>
                     <p>JavaScript | PHP | Go</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
   </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>