<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dr1du2vqp/image/upload/v1554392963/IMG_20190211_081739.jpg" alt="Ogunleye Oluwatosin">
                        <h6>Ogunleye Oluwatosin</h6>
                        <p>Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Ogunley37823156" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/themitope" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ogunleyeoluwatosin" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I am Ogunleye Oluwatosin, I'm a graduate of Computer Science at the University Of Ilorin, I have passion for Web design and development which is why I joined this internship program to learn more on Programming and UI/UX designing </p>
                        <br />
                        <h6>Skills</h6>
                        <p>CSS | PHP | PHP Laravel</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
