<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dwrwxigid/image/upload/v1554409191/9f221550-2734-4c15-bfaf-92eb9d89f212.jpg " alt="Mark Essien">
                        <h6>Thomas Chukwuemeka</h6>
                        <p>Machine language student(HTML,Javascript and Java)</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/@somkeOFfire" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/thetomcats" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@swagsthomas" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hello, I'm TC. I set a task, and I accomplish it, although I don't much yet, I know I'd get there.</p>
                        <br />
                        <h6>Skills</h6>
                        <p> HTML | Java |Javascript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
