<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/timchosen/image/upload/v1554419932/tim_twiiter.jpg" alt="Uzua Timothy">
                        <h6>Uzua Timothy</h6>
                        <p>Back-end Developer</p>
                        <ul class="list">
                           <li><a href="twitter.com/timchosen" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="github.com/timchosen" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="medium.com@timchosen" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>PHP Backend developer with special interests in RESTful API development and also a knack for full-stack development using frameworks such as Symfony, Codeigiter and Laravel. Also avast with mobile app development using Angular/Ionic Frameworks</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML/CSS | PHP | Angular</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
