<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/semiu/image/upload/v1554385651/mypix_1.png" alt="semiu biliaminu">
                        <h6>Semiu Adeyemi Biliainu</h6>
                        <p>Back-End Developer</p>
                        <ul class="list">
                 <li><a href="https://twitter.com/BiliaminuSemiu" target="_blank"<i class="fab fa-twitter"></i></a></li>
                 <li><a href="https://github.com/trustidkid/myfile" target="_blank"<i class="fab fa-github"></i></a></li>
                 <li><a href="https://medium.com/@yemi.bili07/bug-finding-4ee5680d2b01" target="_blank"<i class="fab fa-medium"></i></a></li>
                 </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>An aspiring World Class Solution Provider. through the use of contemporary technological tools. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | Java Android | C# </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>

C:\Program Files\iis express\PHP\v5.3