<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php'; ?>
   <body class=" pi">
      <?php include 'partials/navbar.php'; ?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dv6jo6wsx/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1554388425/IMG_20190331_142456.jpg" alt="Olakanmi Vincent">
                        <h6>Olakanmi Vincent</h6>
                        <p>Fullstack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/@unicode_beast" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/unicodebeast" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@unicodebeast" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                        I am Olakanmi Vincent, an aspiring full stack developer and a Graphics Artist. 
                        I currently work with JavaSript, CorelDraw, Adobe Photoshop and still 
                        advancing my skills and knowledge in different programming Languages. 
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Node.js</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php'; ?>
</html>
