<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dsjdg8t3v/image/upload/a_360/v1554716476/david.jpg" alt="Vaughan David">
                        <h6>Vaughan David</h6>
                        <p>Front-end developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Vaughanda_vid" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/oluwatunbi" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>i am a medical doctor, an aspiring front end developer and tech savvy. i love it when i could write an algorithm to find solutions to the problems around me most expecially when its related to medicine. i have experience with HTML, CSS and javascript. 
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | CSS | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>