<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="http://res.cloudinary.com/webmaye/image/upload/c_crop,x_1,y_1/v1554469895/webmaye.jpg" alt="Soliudeen Ogunsola">
                        <h6>Soliudeen Ogunsola</h6>
                        <p>UI/UX Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/webmaye" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/webmaye" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@webmaye" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Young UI/UX designer passionate about creating visual solutions to people's problem for socioeconomic impact</p>
                        <br />
                        <h6>Skills</h6>
                        <p>UI/UX design | Technical Writing</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
