<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
    <?php include 'partials/navbar.php'; ?>
    <section class="main-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-6 col-xs-12">
                    <div class="col-md-6 col-xs-12">
                        <div class="intern-block border-blue">
                            <img src="https://res.cloudinary.com/modub-com/image/upload/v1554385659/wright_2_t7lhcx.png" alt="Caleb Ogundiya Wright">
                            <h6>Caleb Ogundiya</h6>
                            <p>Software Engineer</p>
                            <ul class="list">
                                <li><a href="https://twitter.com/re_wrighting" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://github.com/wrightkhlebisol" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                                <li><a href="https://medium.com/@wrightkhlebisol" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 align-items-center">
                        <div class="intern-bio border-blue">
                            <h6>About me</h6>
                            <p>Curious, Reserved and Future Oriented. If you are looking for a dose of motivation, coupled with some business and entrepreneurial talk, Hit me up.</p>
                            <br />
                            <h6>Skills</h6>
                            <p>PHP | JavaScript | Python </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</body>
<?php include 'partials/footer.php'; ?>

</html> 