<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/yawmiej/image/upload/v1554448438/lateef.jpg" alt="Abdullateef Abiodun">
                        <h6>Abdullateef Abiodun</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/yellow_codes" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/yawmiej" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@abdullateefabiodunjunior" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I'm Abiodun Abdullateef, a front-end web developer with a passion for problem solving, i am a lover of JavaScript and React, I work well in a team and also independently.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | Sass</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
