<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/yugoisaac/image/upload/v1554457344/me.jpg" alt="Mark Essien">
                        <h6>Ugochukwu Isaac Nwodo</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="www.twitter.com/yugoisaac" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/YugoISAAC" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@YugoISAAC" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>An aspiring Front-End Engineer with years of experience in Graphics Design. I help clients bridge the world of design and technology, bringing design to life, packaging it in an inviting way for users to interact with. I love art and seek harmony between work and life.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | Javascript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
