<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/zayin/image/upload/v1554309383/x.jpg" alt="Xavier Ihee">
                        <h6>Xavier Ihee</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                        <li><a href="https://twitter.com/js_debugger" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Altarmir" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@js_debugger" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A friend of Jesus Christ. I Love building interactive eye candy web applications. I also watch anime and read manga. I would love to visit China, Japan and South Korea someday. Lastly I love continental dishes.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Vanilla JS | React JS | Node JS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
